application: vijayansuwedding-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /images
  static_dir: images

- url: /javascript
  static_dir: javascript

- url: /.*
  script: OurWedding.py